project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    
website:
  title: "IA Generativa"
  sidebar:
    contents:
      - href: index.qmd
        text: Introducción al curso
      - href: ia_generativa.qmd
        text: 1.1 - IA Generativa
      - href: geopolitics.qmd
        text: 1.2 - Geopolítica y la IA
      - href: asistentes.qmd
        text: 2 - Asistentes virtuales
#       - href: investigacion.html
#         text: IA en investigación        
  page-footer:
    left: "&copy; Copyright 2025, Rodrigo Rodrigues-Silveira"
    right: |
      [![](logo_pela.png){fig-alt="Posit" width=500px}](https://oir.org.es/pela/)

        
execute:
  warning: false
  message: false
  error: false

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    toc-depth: 4
    code-fold: show
    code-overflow: wrap
    from: markdown+emoji
  
bibliography: references.bib

editor: source
lang: es
